services:
  mysql:
    image: mysql:8.0
    container_name: like-mysql
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
    ports:
      - "3310:3306"
    volumes:
      - D:/docker-volumes/like-mysql:/var/lib/mysql
